// 文件操作均在远端发布锁内调用；历史资源不混入当前制品。
import { createHash } from "node:crypto";
import {
  cp,
  mkdir,
  readdir,
  readFile,
  writeFile,
  rename,
  symlink,
  readlink,
  rm,
  lstat
} from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";

export async function atomicJson(file, value) {
  await mkdir(path.dirname(file), { recursive: true });
  await writeFile(`${file}.partial`, JSON.stringify(value, null, 2) + "\n");
  await rename(`${file}.partial`, file);
}
export async function point(root, target) {
  await rm(path.join(root, ".current.partial"), { force: true });
  await symlink(target, path.join(root, ".current.partial"));
  await rename(path.join(root, ".current.partial"), path.join(root, "current"));
}
async function files(root, prefix = "") {
  const result = [];
  for (const item of await readdir(path.join(root, prefix), {
    withFileTypes: true
  })) {
    const name = path.join(prefix, item.name);
    if (item.isDirectory()) result.push(...(await files(root, name)));
    else if (item.isFile()) result.push(name);
    else throw new Error(`Unsupported static asset: ${name}`);
  }
  return result;
}
const exists = async (file) =>
  !!(await lstat(file).catch((e) => {
    if (e.code !== "ENOENT") throw e;
  }));
const hash = (bytes) => createHash("sha256").update(bytes).digest("hex");
const assetPath = (component) =>
  component === "admin" ? "assets" : "apps/web/.next/static";

export async function archive(root, artifact, component, id, now = Date.now()) {
  const source = path.join(artifact, assetPath(component));
  const records = {};
  if (await exists(source)) {
    for (const name of await files(source)) {
      const bytes = await readFile(path.join(source, name));
      const dest = path.join(root, "assets", name);
      const digest = hash(bytes);
      if (await exists(dest)) {
        if (hash(await readFile(dest)) !== digest)
          throw new Error(`Static asset collision: ${name}`);
      } else {
        await mkdir(path.dirname(dest), { recursive: true });
        await writeFile(`${dest}.partial`, bytes);
        await rename(`${dest}.partial`, dest);
      }
      records[name] = digest;
    }
  }
  await atomicJson(path.join(root, "history", `${id}.json`), {
    id,
    usedAt: now,
    records
  });
}
export async function bootstrap(root, legacy, component) {
  await mkdir(root, { recursive: true });
  if (await exists(path.join(root, "current"))) return;
  if (!(await exists(legacy)))
    throw new Error(`Missing initial deployment: ${legacy}`);
  // 不移动或改写正在被旧服务读取的目录。
  const dest = path.join(root, "releases", "legacy");
  await rm(dest, { recursive: true, force: true });
  await cp(legacy, dest, { recursive: true, verbatimSymlinks: true });
  await archive(root, dest, component, "legacy");
  await point(root, dest);
}
export async function prune(root, now = Date.now()) {
  const active = path.basename(await readlink(path.join(root, "current")));
  const previous = await readFile(path.join(root, "previous"), "utf8").catch(
    (e) => {
      if (e.code !== "ENOENT") throw e;
      return "";
    }
  );
  const keep = new Set();
  for (const name of await readdir(path.join(root, "history"))) {
    const record = JSON.parse(
      await readFile(path.join(root, "history", name), "utf8")
    );
    if (
      record.id === active ||
      record.id === previous.trim() ||
      now - record.usedAt < 30 * 86400_000
    ) {
      Object.keys(record.records).forEach((file) => keep.add(file));
    } else {
      await rm(path.join(root, "history", name));
      // release IDs are generated by the deployment, never input from clients.
      if (/^[a-zA-Z0-9-]+$/.test(record.id))
        await rm(path.join(root, "releases", record.id), {
          recursive: true,
          force: true
        });
    }
  }
  for (const file of await files(path.join(root, "assets"))) {
    if (!keep.has(file)) await rm(path.join(root, "assets", file));
  }
}
if (
  process.argv[1] &&
  import.meta.url === pathToFileURL(process.argv[1]).href
) {
  const [command, ...args] = process.argv.slice(2);
  const commands = { bootstrap, archive, point, prune };
  if (!commands[command]) throw new Error("Unknown release command");
  await commands[command](...args);
}
